# Make sure golangci-lint is installed.
# https://github.com/golangci/golangci-lint#install
# We can execute `golangci-lint run` for code checking.
run:
  deadline: 6m

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - goimports
    - golint
    - govet
    - ineffassign
    - interfacer
    - misspell
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - lll
    - prealloc
